CREATE USER iotc WITH PASSWORD 'iotc';
CREATE DATABASE core_prod;
GRANT ALL PRIVILEGES ON DATABASE core_prod TO iotc;
CREATE DATABASE appsrv_prod;
GRANT ALL PRIVILEGES ON DATABASE appsrv_prod TO iotc;
