CREATE USER iotc WITH PASSWORD 'iotc';
CREATE DATABASE nwksrv_prod;
GRANT ALL PRIVILEGES ON DATABASE nwksrv_prod TO iotc;
CREATE DATABASE appsrv_prod;
GRANT ALL PRIVILEGES ON DATABASE appsrv_prod TO iotc;
