#!/bin/bash
# 
# post_start
#

set +e

while true; do
  nodetool ping
  EXIT_CODE=$?
  if [ $EXIT_CODE -eq 0 ]; then
    echo "Application is up!"
    break
  fi
done

set -e

echo "Running migrations for core"
bin/iotc rpc Elixir.Core.Release.Tasks migrate
echo "Migrations for core run successfully"

echo "Running migrations for appsrv"
bin/iotc rpc Elixir.Appsrv.Release.Tasks migrate
echo "Migrations for appsrv run successfully"
